/*
You are given two strings 's' and 't'.
String 't' is generated by random shuffling string 's' and then add one more letter at a random position.
Return the letter that was added to 't'.
*/

var findTheDifference = function(s, t) {
    const sArray = s.split("").sort();
    const tArray = t.split("").sort();
    
    for(let i = 0; i <= t.length; i++)
        if(sArray[i] !== tArray[i])
            return tArray[i];
};