/*
You are given two strings 's' and 't'.
String 't' is generated by random shuffling string 's' and then add one more letter at a random position.
Return the letter that was added to 't'.
*/

var findTheDifference = function(s, t) {
    const sa = s.split("").sort();
    const ta = t.split("").sort();
    for(let i = 0; i <= t.length; i++) {
        if(sa[i] != ta[i]) {
            return ta[i];   
        }
    }
};